package kode_project;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author venti
 */
public class homepage extends javax.swing.JFrame {

    /**
     * Creates new form homepage
     */
    public homepage() {
        initComponents();
    }
    int absen_siswa;
    int is_admin;
    public homepage(int absen){
         initComponents();
         absen_siswa = absen;
         
         try {
             String sql = "SELECT * FROM user WHERE absen= ? ";
            java.sql.Connection conn = (java.sql.Connection) koneksi.koneksiDB();
            PreparedStatement psmt = conn.prepareStatement(sql);
            psmt.setInt(1,absen_siswa);
            ResultSet rs = psmt.executeQuery();
            while(rs.next()){
                latestScoreTXT.setText(rs.getString("marks"));
                username.setText(rs.getString("nama"));
                is_admin = rs.getInt("is_admin");
            }
            
            if(is_admin == 1){
                adminBut.setVisible(true);
            } else {
                adminBut.setVisible(false);
            }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        username = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        latestScoreTXT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        codeTXT = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        adminBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1440, 760));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(10, 14, 24));
        jPanel1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(14, 31, 52));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("User");
        jPanel3.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 16, 620, -1));

        jButton4.setBackground(new java.awt.Color(25, 48, 78));
        jButton4.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 102, 51));
        jButton4.setText("LOGOUT");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1086, 6, 216, 63));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("HELLO ");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 17, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, -1));

        jLabel1.setBackground(new java.awt.Color(255, 102, 0));
        jLabel1.setFont(new java.awt.Font("Overwave", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("( Kuis Orang Dongo Enterprise )");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 153, 51));
        jLabel3.setFont(new java.awt.Font("Montserrat", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("WELCOME TO KODE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, 100));

        jPanel2.setBackground(new java.awt.Color(14, 31, 52));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 102, 0));
        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 54)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ENTER QUIZ CODE");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 213, -1, -1));

        latestScoreTXT.setEditable(false);
        latestScoreTXT.setBackground(new java.awt.Color(14, 31, 52));
        latestScoreTXT.setFont(new java.awt.Font("Kristen ITC", 0, 48)); // NOI18N
        latestScoreTXT.setForeground(new java.awt.Color(255, 255, 255));
        latestScoreTXT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        latestScoreTXT.setText("0");
        latestScoreTXT.setBorder(null);
        latestScoreTXT.setCaretColor(new java.awt.Color(255, 102, 51));
        latestScoreTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        latestScoreTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                latestScoreTXTActionPerformed(evt);
            }
        });
        jPanel2.add(latestScoreTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 112, 344, 83));

        jLabel5.setBackground(new java.awt.Color(255, 102, 0));
        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 54)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("LATEST SCORE");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 31, -1, -1));

        codeTXT.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        codeTXT.setForeground(new java.awt.Color(255, 153, 51));
        codeTXT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        codeTXT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        codeTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeTXTActionPerformed(evt);
            }
        });
        jPanel2.add(codeTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 323, 419, 89));

        jButton5.setBackground(new java.awt.Color(25, 48, 78));
        jButton5.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("ENTER ROOM");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 430, 216, 63));

        adminBut.setBackground(new java.awt.Color(25, 48, 78));
        adminBut.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        adminBut.setForeground(new java.awt.Color(255, 255, 255));
        adminBut.setText("ADMIN");
        adminBut.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        adminBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButActionPerformed(evt);
            }
        });
        jPanel2.add(adminBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 500, 216, 63));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 690, 590));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 892));

        setSize(new java.awt.Dimension(1309, 892));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int a = JOptionPane.showConfirmDialog(this, "Are you sure want to logout?", "Select", JOptionPane.OK_CANCEL_OPTION);
        if (a == 0 ){
            this.dispose();
            new login().setVisible(true);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void latestScoreTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_latestScoreTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_latestScoreTXTActionPerformed

    private void codeTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeTXTActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      try {
    String sql = "SELECT * FROM question WHERE QuizID=?";
    java.sql.Connection conn = (java.sql.Connection) koneksi.koneksiDB();
    PreparedStatement psmt = conn.prepareStatement(sql);
    psmt.setString(1, codeTXT.getText());
    ResultSet rs = psmt.executeQuery();
    
    int code = Integer.parseInt(codeTXT.getText());
    if (rs.next()) {
        // Jika ada baris yang ditemukan dengan QuizID yang cocok
        this.dispose();
        new QUIZ(code,absen_siswa).setVisible(true);
    } else {
        // Jika tidak ada baris yang ditemukan
        JOptionPane.showMessageDialog(this, "NO QUIZ FOUND BLOK!!!!!");
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, e);
}

    }//GEN-LAST:event_jButton5ActionPerformed

    private void adminButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButActionPerformed
        this.dispose();
        new dash_admin(absen_siswa).setVisible(true);
    }//GEN-LAST:event_adminButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminBut;
    private javax.swing.JTextField codeTXT;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField latestScoreTXT;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
